import {
  mdiAccountGroup,
  mdiAccountOutline,
  mdiAccountPlusOutline,
  mdiArmFlex,
  mdiBagPersonal,
  mdiBrush,
  mdiCalendarBlankOutline,
  mdiClockOutline,
  mdiCheck,
  mdiChevronDoubleLeft,
  mdiChevronDoubleRight,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiClipboardCheckOutline,
  mdiCodeTags,
  mdiContentCut,
  mdiDna,
  mdiDraw,
  mdiEarHearing,
  mdiEmoticonHappyOutline,
  mdiEqualizer,
  mdiEyeOutline,
  mdiFaceMan,
  mdiFaceManOutline,
  mdiFaceManProfile,
  mdiFaceRecognition,
  mdiGesture,
  mdiGlasses,
  mdiGuyFawkesMask,
  mdiHanger,
  mdiHatFedora,
  mdiHeadOutline,
  mdiHumanHandsdown,
  mdiHumanMale,
  mdiInformationOutline,
  mdiLipstick,
  mdiLoginVariant,
  mdiMonitorOff,
  mdiMustache,
  mdiNecklace,
  mdiPause,
  mdiPlay,
  mdiPlus,
  mdiRing,
  mdiShoeSneaker,
  mdiSkipNext,
  mdiSkipPrevious,
  mdiSunglasses,
  mdiTie,
  mdiTrashCanOutline,
  mdiTshirtCrew,
  mdiTshirtCrewOutline,
  mdiViewDashboardOutline,
  mdiVolumeHigh,
  mdiVolumeMedium,
  mdiVolumeOff,
  mdiWalk,
  mdiWatch,
  mdiWaves,
  mdiWeatherSunny,
} from '@mdi/js'

export const DEFAULT_ICON_PATH = mdiAccountGroup

const ICON_PATHS: Record<string, string> = {
  'mdi-account-group': mdiAccountGroup,
  'mdi-account-outline': mdiAccountOutline,
  'mdi-account-plus-outline': mdiAccountPlusOutline,
  'mdi-calendar-blank-outline': mdiCalendarBlankOutline,
  'mdi-check': mdiCheck,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-login-variant': mdiLoginVariant,
  'mdi-chevron-double-left': mdiChevronDoubleLeft,
  'mdi-chevron-double-right': mdiChevronDoubleRight,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-arm-flex': mdiArmFlex,
  'mdi-bag-personal': mdiBagPersonal,
  'mdi-brush': mdiBrush,
  'mdi-clock-outline': mdiClockOutline,
  'mdi-clipboard-check-outline': mdiClipboardCheckOutline,
  'mdi-code-tags': mdiCodeTags,
  'mdi-content-cut': mdiContentCut,
  'mdi-dna': mdiDna,
  'mdi-draw': mdiDraw,
  'mdi-ear-hearing': mdiEarHearing,
  'mdi-emoticon-happy-outline': mdiEmoticonHappyOutline,
  'mdi-equalizer': mdiEqualizer,
  'mdi-eye-outline': mdiEyeOutline,
  'mdi-face-man': mdiFaceMan,
  'mdi-face-man-outline': mdiFaceManOutline,
  'mdi-face-man-profile': mdiFaceManProfile,
  'mdi-face-recognition': mdiFaceRecognition,
  'mdi-gesture': mdiGesture,
  'mdi-glasses': mdiGlasses,
  'mdi-guy-fawkes-mask': mdiGuyFawkesMask,
  'mdi-hanger': mdiHanger,
  'mdi-hat-fedora': mdiHatFedora,
  'mdi-head-outline': mdiHeadOutline,
  'mdi-human-handsdown': mdiHumanHandsdown,
  'mdi-human-male': mdiHumanMale,
  'mdi-lipstick': mdiLipstick,
  'mdi-mustache': mdiMustache,
  'mdi-necklace': mdiNecklace,
  'mdi-ring': mdiRing,
  'mdi-shoe-sneaker': mdiShoeSneaker,
  'mdi-sunglasses': mdiSunglasses,
  'mdi-tie': mdiTie,
  'mdi-tshirt-crew': mdiTshirtCrew,
  'mdi-tshirt-crew-outline': mdiTshirtCrewOutline,
  'mdi-walk': mdiWalk,
  'mdi-watch': mdiWatch,
  'mdi-waves': mdiWaves,
  'mdi-weather-sunny': mdiWeatherSunny,
  'mdi-monitor-off': mdiMonitorOff,
  'mdi-pause': mdiPause,
  'mdi-play': mdiPlay,
  'mdi-plus': mdiPlus,
  'mdi-skip-next': mdiSkipNext,
  'mdi-skip-previous': mdiSkipPrevious,
  'mdi-trash-can-outline': mdiTrashCanOutline,
  'mdi-view-dashboard-outline': mdiViewDashboardOutline,
  'mdi-volume-high': mdiVolumeHigh,
  'mdi-volume-medium': mdiVolumeMedium,
  'mdi-volume-off': mdiVolumeOff,
}

export const resolveIcon = (name: string | undefined): string | undefined => {
  if (!name) {
    return undefined
  }
  return ICON_PATHS[name] ?? DEFAULT_ICON_PATH
}
