export type AppearanceControlType = 'select' | 'slider' | 'swatches' | 'blend' | 'sprite'

export interface AppearanceControl {
  id: string
  labelKey: string
  type: AppearanceControlType
  max?: number
  min?: number
  colors?: string[]
  labels?: string[]
  portrait?: boolean
  section?: string
  leftKey?: string
  rightKey?: string
  unit?: string
  step?: number
  defaultValue?: number
  sprite?: string
  spriteColumns?: number
}

export interface AppearanceCategory {
  id: string
  labelKey: string
  icon: string
  group?: string
  controls: AppearanceControl[]
}

export interface AppearanceStepDefinition {
  id: string
  icon: string
  labelKey: string
  subtitleKey: string
  categories?: AppearanceCategory[]
}

export interface PedModel {
  id: string
  labelKey?: string
  name?: string
}

export const PED_MODELS: PedModel[] = [
  { id: 'mp_m_freemode_01', labelKey: 'appearance.pedMale' },
  { id: 'mp_f_freemode_01', labelKey: 'appearance.pedFemale' },
  { id: 'a_m_y_skater_01', name: 'A_M_Y_Skater_01' },
  { id: 'a_m_y_hipster_02', name: 'A_M_Y_Hipster_02' },
  { id: 'a_f_y_tourist_01', name: 'A_F_Y_Tourist_01' },
  { id: 'a_m_m_business_01', name: 'A_M_M_Business_01' },
  { id: 'a_f_y_business_02', name: 'A_F_Y_Business_02' },
  { id: 'a_m_y_beach_01', name: 'A_M_Y_Beach_01' },
  { id: 'a_f_y_fitness_02', name: 'A_F_Y_Fitness_02' },
  { id: 'a_m_m_farmer_01', name: 'A_M_M_Farmer_01' },
  { id: 'a_f_m_bodybuild_01', name: 'A_F_M_BodyBuild_01' },
  { id: 'a_m_y_golfer_01', name: 'A_M_Y_Golfer_01' },
  { id: 'a_f_y_hipster_01', name: 'A_F_Y_Hipster_01' },
  { id: 'a_m_m_skidrow_01', name: 'A_M_M_Skidrow_01' },
  { id: 'a_f_y_runner_01', name: 'A_F_Y_Runner_01' },
  { id: 'a_m_y_vinewood_03', name: 'A_M_Y_Vinewood_03' },
  { id: 's_m_y_cop_01', name: 'S_M_Y_Cop_01' },
]

const HAIR_COLORS = [
  '#1c1f21',
  '#272a2c',
  '#312e2c',
  '#35261c',
  '#4b321f',
  '#5c3b24',
  '#6d4c35',
  '#6b503b',
  '#765c45',
  '#7f684e',
  '#99815d',
  '#a79369',
  '#af9c70',
  '#bba063',
  '#d6b97b',
  '#dac38e',
  '#9f7f59',
  '#845039',
  '#682b1f',
  '#61120c',
  '#640f0a',
  '#7c140f',
  '#a02e19',
  '#b64b28',
  '#a2502f',
  '#aa4e2b',
  '#626262',
  '#808080',
  '#aaaaaa',
  '#c5c5c5',
  '#463955',
  '#5a3f6b',
  '#763c76',
  '#ed74e3',
  '#eb4b93',
  '#f299bc',
  '#04959e',
  '#025f86',
  '#023974',
  '#3fa16a',
  '#217c61',
  '#185c55',
  '#b6c034',
  '#70a90b',
  '#439d13',
  '#dcb857',
  '#e5b103',
  '#e69102',
  '#f28831',
  '#fb8057',
  '#e28b58',
  '#d1593c',
  '#ce3120',
  '#ad0903',
  '#880302',
  '#1f1814',
  '#291f19',
  '#2e221b',
  '#37291e',
  '#2e2218',
  '#231b15',
  '#020202',
  '#706c66',
  '#9d7a50',
]

const MAKEUP_COLORS = [
  '#992532',
  '#c8395d',
  '#bd516c',
  '#b8637a',
  '#a6526b',
  '#b1434c',
  '#7f3133',
  '#a4645d',
  '#c18779',
  '#cba096',
  '#c6918f',
  '#ab6f63',
  '#b06050',
  '#a84c33',
  '#b47178',
  '#ca7f92',
  '#ed9cbe',
  '#e775a4',
  '#de3e81',
  '#b34c6e',
  '#712739',
  '#4f1f2a',
  '#aa222f',
  '#de2034',
  '#cf0813',
  '#e55470',
  '#dc3fb5',
  '#c227b2',
  '#a01ca9',
  '#6e1875',
  '#731465',
  '#56165c',
  '#6d1a9d',
  '#1b3771',
  '#1d4ea7',
  '#1e74bb',
  '#21a3ce',
  '#25c2d2',
  '#23cca5',
  '#27c07d',
  '#1b9c32',
  '#148604',
  '#70d041',
  '#c5ea34',
  '#e1e32f',
  '#ffdd26',
  '#fac026',
  '#f78a27',
  '#fe5910',
  '#be6e19',
  '#f7c97f',
  '#fbe5c0',
  '#f5f5f5',
  '#b3b4b3',
  '#919191',
  '#564e4e',
  '#180e0e',
  '#58969e',
  '#4d6f8c',
  '#1a2b55',
  '#a07e6b',
  '#826355',
  '#6d5346',
  '#3e2d27',
]

const HERITAGE_CATEGORIES: AppearanceCategory[] = [
  {
    id: 'parents',
    labelKey: 'appearance.catParents',
    icon: 'mdi-account-group',
    controls: [
      {
        id: 'mother',
        labelKey: 'appearance.ctrlMother',
        type: 'select',
        portrait: true,
      },
      {
        id: 'father',
        labelKey: 'appearance.ctrlFather',
        type: 'select',
        portrait: true,
      },
    ],
  },
  {
    id: 'resemblance',
    labelKey: 'appearance.catResemblance',
    icon: 'mdi-dna',
    controls: [
      {
        id: 'resemblance',
        labelKey: 'appearance.ctrlResemblance',
        type: 'blend',
        min: 0,
        max: 100,
        leftKey: 'appearance.ctrlMother',
        rightKey: 'appearance.ctrlFather',
      },
      {
        id: 'skinTone',
        labelKey: 'appearance.ctrlSkinTone',
        type: 'blend',
        min: 0,
        max: 100,
        leftKey: 'appearance.ctrlMother',
        rightKey: 'appearance.ctrlFather',
      },
    ],
  },
]

const PHYSICAL_CATEGORIES: AppearanceCategory[] = [
  {
    id: 'hair',
    labelKey: 'appearance.catHair',
    icon: 'mdi-content-cut',
    group: 'appearance.groupHairiness',
    controls: [
      {
        id: 'style',
        labelKey: 'appearance.ctrlHairstyle',
        type: 'slider',
        min: 1,
        max: 38,
        unit: '/ 38',
        defaultValue: 1,
      },
      { id: 'color', labelKey: 'appearance.ctrlColor', type: 'swatches', colors: HAIR_COLORS },
      {
        id: 'highlights',
        labelKey: 'appearance.ctrlHighlights',
        type: 'swatches',
        colors: HAIR_COLORS,
      },
    ],
  },
  {
    id: 'eyebrows',
    labelKey: 'appearance.catEyebrows',
    icon: 'mdi-gesture',
    group: 'appearance.groupHairiness',
    controls: [
      {
        id: 'shape',
        labelKey: 'appearance.ctrlShape',
        type: 'slider',
        min: 1,
        max: 34,
        unit: '/ 34',
        defaultValue: 1,
      },
      { id: 'color', labelKey: 'appearance.ctrlColor', type: 'swatches', colors: HAIR_COLORS },
      {
        id: 'opacity',
        labelKey: 'appearance.ctrlOpacity',
        type: 'slider',
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.5,
        leftKey: 'appearance.poleSparse',
        rightKey: 'appearance.poleStrong',
      },
      {
        id: 'height',
        labelKey: 'appearance.ctrlBrowHeight',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleClose',
        rightKey: 'appearance.poleFar',
      },
      {
        id: 'depth',
        labelKey: 'appearance.ctrlBrowDepth',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleSunken',
        rightKey: 'appearance.poleProminent',
      },
    ],
  },
  {
    id: 'beard',
    labelKey: 'appearance.catBeard',
    icon: 'mdi-mustache',
    group: 'appearance.groupHairiness',
    controls: [
      {
        id: 'style',
        labelKey: 'appearance.ctrlStyle',
        type: 'slider',
        min: 1,
        max: 29,
        unit: '/ 29',
        defaultValue: 1,
      },
      { id: 'color', labelKey: 'appearance.ctrlColor', type: 'swatches', colors: HAIR_COLORS },
      {
        id: 'opacity',
        labelKey: 'appearance.ctrlOpacity',
        type: 'slider',
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.5,
        leftKey: 'appearance.poleSparse',
        rightKey: 'appearance.poleStrong',
      },
    ],
  },
  {
    id: 'chestHair',
    labelKey: 'appearance.catChestHair',
    icon: 'mdi-waves',
    group: 'appearance.groupHairiness',
    controls: [
      {
        id: 'style',
        labelKey: 'appearance.ctrlStyle',
        type: 'slider',
        min: 1,
        max: 17,
        unit: '/ 17',
        defaultValue: 1,
      },
      { id: 'color', labelKey: 'appearance.ctrlColor', type: 'swatches', colors: HAIR_COLORS },
      {
        id: 'opacity',
        labelKey: 'appearance.ctrlOpacity',
        type: 'slider',
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.5,
        leftKey: 'appearance.poleSparse',
        rightKey: 'appearance.poleHairy',
      },
    ],
  },
  {
    id: 'eyes',
    labelKey: 'appearance.catEyes',
    icon: 'mdi-eye-outline',
    group: 'appearance.groupFace',
    controls: [
      {
        id: 'opening',
        labelKey: 'appearance.ctrlOpening',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleNarrow',
        rightKey: 'appearance.poleWide',
      },
      {
        id: 'style',
        labelKey: 'appearance.ctrlEyeStyle',
        type: 'sprite',
        sprite: 'eyeColour',
        max: 32,
        spriteColumns: 8,
      },
    ],
  },
  {
    id: 'nose',
    labelKey: 'appearance.catNose',
    icon: 'mdi-face-recognition',
    group: 'appearance.groupFace',
    controls: [
      {
        id: 'width',
        labelKey: 'appearance.ctrlNoseWidth',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleNarrow',
        rightKey: 'appearance.poleWide',
      },
      {
        id: 'height',
        labelKey: 'appearance.ctrlNoseHeight',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleLow',
        rightKey: 'appearance.poleHigh',
      },
      {
        id: 'length',
        labelKey: 'appearance.ctrlNoseLength',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleShort',
        rightKey: 'appearance.poleLong',
      },
      {
        id: 'bridgeHeight',
        labelKey: 'appearance.ctrlNoseBridgeHeight',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleLow',
        rightKey: 'appearance.poleHigh',
      },
      {
        id: 'bridgeTwist',
        labelKey: 'appearance.ctrlNoseBridgeTwist',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleLeft',
        rightKey: 'appearance.poleRight',
      },
      {
        id: 'tipHeight',
        labelKey: 'appearance.ctrlNoseTipHeight',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleLow',
        rightKey: 'appearance.poleHigh',
      },
    ],
  },
  {
    id: 'cheeks',
    labelKey: 'appearance.catCheeks',
    icon: 'mdi-emoticon-happy-outline',
    group: 'appearance.groupFace',
    controls: [
      {
        id: 'boneHeight',
        labelKey: 'appearance.ctrlCheekboneHeight',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleLow',
        rightKey: 'appearance.poleHigh',
      },
      {
        id: 'boneWidth',
        labelKey: 'appearance.ctrlCheekboneWidth',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleNarrow',
        rightKey: 'appearance.poleWide',
      },
      {
        id: 'width',
        labelKey: 'appearance.ctrlCheekWidth',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleGaunt',
        rightKey: 'appearance.polePuffy',
      },
    ],
  },
  {
    id: 'lips',
    labelKey: 'appearance.catLips',
    icon: 'mdi-lipstick',
    group: 'appearance.groupFace',
    controls: [
      {
        id: 'thickness',
        labelKey: 'appearance.ctrlLipThickness',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleThin',
        rightKey: 'appearance.poleThick',
      },
    ],
  },
  {
    id: 'jaw',
    labelKey: 'appearance.catJaw',
    icon: 'mdi-face-man-profile',
    group: 'appearance.groupFace',
    controls: [
      {
        id: 'width',
        labelKey: 'appearance.ctrlJawWidth',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleNarrow',
        rightKey: 'appearance.poleWide',
      },
      {
        id: 'length',
        labelKey: 'appearance.ctrlJawLength',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleShort',
        rightKey: 'appearance.poleLong',
      },
    ],
  },
  {
    id: 'chin',
    labelKey: 'appearance.catChin',
    icon: 'mdi-face-man',
    group: 'appearance.groupFace',
    controls: [
      {
        id: 'position',
        labelKey: 'appearance.ctrlChinPosition',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleLowered',
        rightKey: 'appearance.poleRaised',
      },
      {
        id: 'length',
        labelKey: 'appearance.ctrlChinLength',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleShort',
        rightKey: 'appearance.poleLong',
      },
      {
        id: 'width',
        labelKey: 'appearance.ctrlChinWidth',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleNarrow',
        rightKey: 'appearance.poleWide',
      },
      {
        id: 'hollow',
        labelKey: 'appearance.ctrlChinHollow',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleSmooth',
        rightKey: 'appearance.poleProminent',
      },
    ],
  },
  {
    id: 'neck',
    labelKey: 'appearance.catNeck',
    icon: 'mdi-tie',
    group: 'appearance.groupFace',
    controls: [
      {
        id: 'thickness',
        labelKey: 'appearance.ctrlNeckThickness',
        type: 'slider',
        min: -1,
        max: 1,
        step: 0.05,
        defaultValue: 0,
        leftKey: 'appearance.poleThin',
        rightKey: 'appearance.poleThick',
      },
    ],
  },
  {
    id: 'ageing',
    labelKey: 'appearance.catAgeing',
    icon: 'mdi-clock-outline',
    group: 'appearance.groupSkin',
    controls: [
      {
        id: 'style',
        labelKey: 'appearance.ctrlAgeingType',
        type: 'slider',
        min: 1,
        max: 15,
        unit: '/ 15',
        defaultValue: 1,
      },
      {
        id: 'opacity',
        labelKey: 'appearance.ctrlOpacity',
        type: 'slider',
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.5,
        leftKey: 'appearance.poleSubtle',
        rightKey: 'appearance.poleProminent',
      },
    ],
  },
  {
    id: 'makeup',
    labelKey: 'appearance.catMakeup',
    icon: 'mdi-brush',
    group: 'appearance.groupSkin',
    controls: [
      {
        id: 'lipstickStyle',
        section: 'appearance.secLipstick',
        labelKey: 'appearance.ctrlStyle',
        type: 'slider',
        min: 1,
        max: 10,
        unit: '/ 10',
        defaultValue: 1,
      },
      {
        id: 'lipstickColor',
        labelKey: 'appearance.ctrlColor',
        type: 'swatches',
        colors: MAKEUP_COLORS,
      },
      {
        id: 'lipstickOpacity',
        labelKey: 'appearance.ctrlOpacity',
        type: 'slider',
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.5,
        leftKey: 'appearance.poleSubtle',
        rightKey: 'appearance.poleProminent',
      },
      {
        id: 'makeupStyle',
        section: 'appearance.secMakeup',
        labelKey: 'appearance.ctrlStyle',
        type: 'slider',
        min: 1,
        max: 75,
        unit: '/ 75',
        defaultValue: 1,
      },
      {
        id: 'makeupPrimaryColor',
        labelKey: 'appearance.ctrlPrimaryColor',
        type: 'swatches',
        colors: MAKEUP_COLORS,
      },
      {
        id: 'makeupSecondaryColor',
        labelKey: 'appearance.ctrlSecondaryColor',
        type: 'swatches',
        colors: MAKEUP_COLORS,
      },
      {
        id: 'makeupOpacity',
        labelKey: 'appearance.ctrlOpacity',
        type: 'slider',
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.5,
        leftKey: 'appearance.poleSubtle',
        rightKey: 'appearance.poleProminent',
      },
      {
        id: 'blushStyle',
        section: 'appearance.secBlush',
        labelKey: 'appearance.ctrlStyle',
        type: 'slider',
        min: 1,
        max: 7,
        unit: '/ 7',
        defaultValue: 1,
      },
      {
        id: 'blushColor',
        labelKey: 'appearance.ctrlColor',
        type: 'swatches',
        colors: MAKEUP_COLORS,
      },
      {
        id: 'blushOpacity',
        labelKey: 'appearance.ctrlOpacity',
        type: 'slider',
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.5,
        leftKey: 'appearance.poleSubtle',
        rightKey: 'appearance.poleProminent',
      },
    ],
  },
  {
    id: 'skinDamage',
    labelKey: 'appearance.catSkinDamage',
    icon: 'mdi-weather-sunny',
    group: 'appearance.groupSkin',
    controls: [
      {
        id: 'sunDamageStyle',
        section: 'appearance.secSunDamage',
        labelKey: 'appearance.ctrlSunDamageType',
        type: 'slider',
        min: 1,
        max: 11,
        unit: '/ 11',
        defaultValue: 1,
      },
      {
        id: 'sunDamageOpacity',
        labelKey: 'appearance.ctrlOpacity',
        type: 'slider',
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.5,
        leftKey: 'appearance.poleSubtle',
        rightKey: 'appearance.poleProminent',
      },
      {
        id: 'molesStyle',
        section: 'appearance.secMoles',
        labelKey: 'appearance.ctrlMoleType',
        type: 'slider',
        min: 1,
        max: 18,
        unit: '/ 18',
        defaultValue: 1,
      },
      {
        id: 'molesOpacity',
        labelKey: 'appearance.ctrlOpacity',
        type: 'slider',
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.5,
        leftKey: 'appearance.poleSubtle',
        rightKey: 'appearance.poleProminent',
      },
      {
        id: 'blemishesStyle',
        section: 'appearance.secBlemishes',
        labelKey: 'appearance.ctrlBlemishType',
        type: 'slider',
        min: 1,
        max: 24,
        unit: '/ 24',
        defaultValue: 1,
      },
      {
        id: 'blemishesOpacity',
        labelKey: 'appearance.ctrlOpacity',
        type: 'slider',
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.5,
        leftKey: 'appearance.poleSubtle',
        rightKey: 'appearance.poleProminent',
      },
    ],
  },
]

const CLOTHING_CATEGORIES: AppearanceCategory[] = [
  {
    id: 'jacket',
    labelKey: 'appearance.catJacket',
    icon: 'mdi-hanger',
    controls: [
      {
        id: 'model',
        labelKey: 'appearance.ctrlJacketStyle',
        type: 'slider',
        min: 1,
        max: 61,
        unit: '/ 61',
        defaultValue: 1,
      },
      {
        id: 'variant',
        labelKey: 'appearance.ctrlJacketVariant',
        type: 'slider',
        min: 1,
        max: 8,
        unit: '/ 8',
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'tshirt',
    labelKey: 'appearance.catTshirt',
    icon: 'mdi-tshirt-crew-outline',
    controls: [
      {
        id: 'model',
        labelKey: 'appearance.ctrlTshirtStyle',
        type: 'slider',
        min: 1,
        max: 111,
        unit: '/ 111',
        defaultValue: 1,
      },
      {
        id: 'variant',
        labelKey: 'appearance.ctrlTshirtVariant',
        type: 'slider',
        min: 1,
        max: 12,
        unit: '/ 12',
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'armsGloves',
    labelKey: 'appearance.catArmsGloves',
    icon: 'mdi-arm-flex',
    controls: [
      {
        id: 'model',
        labelKey: 'appearance.ctrlArmsStyle',
        type: 'slider',
        min: 1,
        max: 17,
        unit: '/ 17',
        defaultValue: 1,
      },
      {
        id: 'variant',
        labelKey: 'appearance.ctrlArmsVariant',
        type: 'slider',
        min: 1,
        max: 6,
        unit: '/ 6',
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'pants',
    labelKey: 'appearance.catPants',
    icon: 'mdi-human-male',
    controls: [
      {
        id: 'model',
        labelKey: 'appearance.ctrlPantsStyle',
        type: 'slider',
        min: 1,
        max: 98,
        unit: '/ 98',
        defaultValue: 1,
      },
      {
        id: 'variant',
        labelKey: 'appearance.ctrlPantsVariant',
        type: 'slider',
        min: 1,
        max: 10,
        unit: '/ 10',
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'shoes',
    labelKey: 'appearance.catShoes',
    icon: 'mdi-shoe-sneaker',
    controls: [
      {
        id: 'model',
        labelKey: 'appearance.ctrlShoesStyle',
        type: 'slider',
        min: 1,
        max: 77,
        unit: '/ 77',
        defaultValue: 1,
      },
      {
        id: 'variant',
        labelKey: 'appearance.ctrlShoesVariant',
        type: 'slider',
        min: 1,
        max: 10,
        unit: '/ 10',
        defaultValue: 1,
      },
    ],
  },
]

const ACCESSORY_CATEGORIES: AppearanceCategory[] = [
  {
    id: 'mask',
    labelKey: 'appearance.catMask',
    icon: 'mdi-guy-fawkes-mask',
    controls: [
      {
        id: 'model',
        labelKey: 'appearance.ctrlMaskStyle',
        type: 'slider',
        min: 1,
        max: 53,
        unit: '/ 53',
        defaultValue: 1,
      },
      {
        id: 'variant',
        labelKey: 'appearance.ctrlMaskVariant',
        type: 'slider',
        min: 1,
        max: 8,
        unit: '/ 8',
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'backpack',
    labelKey: 'appearance.catBackpack',
    icon: 'mdi-bag-personal',
    controls: [
      {
        id: 'model',
        labelKey: 'appearance.ctrlBackpackStyle',
        type: 'slider',
        min: 1,
        max: 40,
        unit: '/ 40',
        defaultValue: 1,
      },
      {
        id: 'variant',
        labelKey: 'appearance.ctrlBackpackVariant',
        type: 'slider',
        min: 1,
        max: 6,
        unit: '/ 6',
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'hat',
    labelKey: 'appearance.catHat',
    icon: 'mdi-hat-fedora',
    controls: [
      {
        id: 'model',
        labelKey: 'appearance.ctrlHatStyle',
        type: 'slider',
        min: 1,
        max: 91,
        unit: '/ 91',
        defaultValue: 1,
      },
      {
        id: 'variant',
        labelKey: 'appearance.ctrlHatVariant',
        type: 'slider',
        min: 1,
        max: 8,
        unit: '/ 8',
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'glasses',
    labelKey: 'appearance.catGlasses',
    icon: 'mdi-glasses',
    controls: [
      {
        id: 'model',
        labelKey: 'appearance.ctrlGlassesStyle',
        type: 'slider',
        min: 1,
        max: 41,
        unit: '/ 41',
        defaultValue: 1,
      },
      {
        id: 'variant',
        labelKey: 'appearance.ctrlGlassesVariant',
        type: 'slider',
        min: 1,
        max: 10,
        unit: '/ 10',
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'earrings',
    labelKey: 'appearance.catEarrings',
    icon: 'mdi-ear-hearing',
    controls: [
      {
        id: 'model',
        labelKey: 'appearance.ctrlEarringsStyle',
        type: 'slider',
        min: 1,
        max: 31,
        unit: '/ 31',
        defaultValue: 1,
      },
      {
        id: 'variant',
        labelKey: 'appearance.ctrlEarringsVariant',
        type: 'slider',
        min: 1,
        max: 4,
        unit: '/ 4',
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'watch',
    labelKey: 'appearance.catWatch',
    icon: 'mdi-watch',
    controls: [
      {
        id: 'model',
        labelKey: 'appearance.ctrlWatchStyle',
        type: 'slider',
        min: 1,
        max: 27,
        unit: '/ 27',
        defaultValue: 1,
      },
      {
        id: 'variant',
        labelKey: 'appearance.ctrlWatchVariant',
        type: 'slider',
        min: 1,
        max: 6,
        unit: '/ 6',
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'bracelet',
    labelKey: 'appearance.catBracelet',
    icon: 'mdi-ring',
    controls: [
      {
        id: 'model',
        labelKey: 'appearance.ctrlBraceletStyle',
        type: 'slider',
        min: 1,
        max: 19,
        unit: '/ 19',
        defaultValue: 1,
      },
      {
        id: 'variant',
        labelKey: 'appearance.ctrlBraceletVariant',
        type: 'slider',
        min: 1,
        max: 4,
        unit: '/ 4',
        defaultValue: 1,
      },
    ],
  },
  {
    id: 'neckwear',
    labelKey: 'appearance.catNeckwear',
    icon: 'mdi-necklace',
    controls: [
      {
        id: 'model',
        labelKey: 'appearance.ctrlNeckwearStyle',
        type: 'slider',
        min: 1,
        max: 43,
        unit: '/ 43',
        defaultValue: 1,
      },
      {
        id: 'variant',
        labelKey: 'appearance.ctrlNeckwearVariant',
        type: 'slider',
        min: 1,
        max: 6,
        unit: '/ 6',
        defaultValue: 1,
      },
    ],
  },
]

const TATTOO_ZONES = [
  { id: 'hair', labelKey: 'appearance.catHair', icon: 'mdi-content-cut' },
  { id: 'head', labelKey: 'appearance.catHead', icon: 'mdi-head-outline' },
  { id: 'neck', labelKey: 'appearance.catNeck', icon: 'mdi-tie' },
  { id: 'torso', labelKey: 'appearance.catTorso', icon: 'mdi-tshirt-crew' },
  { id: 'back', labelKey: 'appearance.catBack', icon: 'mdi-human-handsdown' },
  { id: 'leftArm', labelKey: 'appearance.catLeftArm', icon: 'mdi-arm-flex' },
  { id: 'rightArm', labelKey: 'appearance.catRightArm', icon: 'mdi-arm-flex' },
  { id: 'leftLeg', labelKey: 'appearance.catLeftLeg', icon: 'mdi-walk' },
  { id: 'rightLeg', labelKey: 'appearance.catRightLeg', icon: 'mdi-walk' },
]

const TATTOO_CATEGORIES: AppearanceCategory[] = TATTOO_ZONES.map((zone) => ({
  id: zone.id,
  labelKey: zone.labelKey,
  icon: zone.icon,
  controls: [
    {
      id: 'tattoo',
      labelKey: 'appearance.ctrlTattoo',
      type: 'slider',
      min: 1,
      max: 21,
      unit: '/ 21',
      defaultValue: 1,
    },
  ],
}))

export const APPEARANCE_STEPS: AppearanceStepDefinition[] = [
  {
    id: 'ped',
    icon: 'mdi-account-outline',
    labelKey: 'appearance.stepPed',
    subtitleKey: 'appearance.stepPedSubtitle',
  },
  {
    id: 'heritage',
    icon: 'mdi-dna',
    labelKey: 'appearance.stepHeritage',
    subtitleKey: 'appearance.stepHeritageSubtitle',
    categories: HERITAGE_CATEGORIES,
  },
  {
    id: 'physical',
    icon: 'mdi-face-man-outline',
    labelKey: 'appearance.stepPhysical',
    subtitleKey: 'appearance.stepPhysicalSubtitle',
    categories: PHYSICAL_CATEGORIES,
  },
  {
    id: 'clothing',
    icon: 'mdi-tshirt-crew-outline',
    labelKey: 'appearance.stepClothing',
    subtitleKey: 'appearance.stepClothingSubtitle',
    categories: CLOTHING_CATEGORIES,
  },
  {
    id: 'accessories',
    icon: 'mdi-sunglasses',
    labelKey: 'appearance.stepAccessories',
    subtitleKey: 'appearance.stepAccessoriesSubtitle',
    categories: ACCESSORY_CATEGORIES,
  },
  {
    id: 'tattoos',
    icon: 'mdi-draw',
    labelKey: 'appearance.stepTattoos',
    subtitleKey: 'appearance.stepTattoosSubtitle',
    categories: TATTOO_CATEGORIES,
  },
  {
    id: 'summary',
    icon: 'mdi-clipboard-check-outline',
    labelKey: 'appearance.stepSummary',
    subtitleKey: 'appearance.stepSummarySubtitle',
  },
]

export const controlKey = (stepId: string, categoryId: string, controlId: string): string =>
  `${stepId}.${categoryId}.${controlId}`

export const createAppearanceDraft = (): Record<string, number> => {
  const draft: Record<string, number> = {}
  for (const step of APPEARANCE_STEPS) {
    for (const category of step.categories ?? []) {
      for (const control of category.controls) {
        if (control.defaultValue !== undefined) {
          draft[controlKey(step.id, category.id, control.id)] = control.defaultValue
        } else if (control.type === 'slider' || control.type === 'blend') {
          draft[controlKey(step.id, category.id, control.id)] = Math.round(
            ((control.min ?? 0) + (control.max ?? 100)) / 2,
          )
        } else {
          draft[controlKey(step.id, category.id, control.id)] = 0
        }
      }
    }
  }
  return draft
}
